version: "3"

services:
  database:
    build: ./
    container_name: schwertbot-db
    ports:
      - "6666:5432"
    env_file:
      - ./database.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
